### ISSUE TITLE
Error on creating a new style prototype

### ISSUE THREAD

**Issue by nicxvan** [north/generator-style-prototype#10]
Error: spawn ENOENT
    at errnoException (child_process.js:980:11)
    at Process.ChildProcess._handle.onexit (child_process.js:771:34)

Most of the files are there but then if I try to spin up the Grunt server I get a fatal error as well. Grunt is in the path and there is a gruntfile.js in the prototype.

**Comment by nicxvan** [comment]
This was a really non-standard configuration trying to get it working on cygwin which node.js doesn't support.
