### ISSUE TITLE
Apostrophe in company name

### ISSUE THREAD

**Issue by scottnath** [north/generator-style-prototype#42]
Hey @Snugug ,

Today I tried to set up a new SP with a company that had an apostrophe in its name. When I ran `grunt server` both uglify and jshint hated it and threw errors (which I saw by using --force.)

```
Running "uglify:dev" (uglify) task
{ message: 'Unexpected token name «s», expected punc «,»',
  line: 1,
  col: 25,
  pos: 25,
  stack: 'Error\n    at new JS_Parse_Error (/Users/triphere/Sites/prohibitions-end/style-prototype/prohibitions-end/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:196:18)\n    at js_error (/Users/triphere/Sites/prohibitions-end/style-prototype/prohibitions-end/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:204:11)\n    at croak (/Users/triphere/Sites/prohibitions-end/style-prototype/prohibitions-end/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:663:9)\n    at token_error (/Users/triphere/Sites/prohibitions-end/style-prototype/prohibitions-end/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:671:9)\n    at expect_token (/Users/triphere/Sites/prohibitions-end/style-prototype/prohibitions-end/node_modules/grunt-contrib-uglify/node_modules/uglify-js/lib/parse.js:684:9)\n   
...
etc
...
>> Uglifying source "js/main.js" failed.
Warning: Uglification failed.
Unexpected token name «s», expected punc «,».
Line 1 in js/main.js
 Used --force, continuing.
Warning: Cannot read property 'min' of undefined Used --force, continuing.

Running "generator:dev" (generator) task
>> new: colors/index.html
>> new: components/index.html
>> new: content/article/index.html
>> new: content/human-interest-story/index.html
>> new: content/index.html
>> new: content/vision/index.html
>> new: elements/index.html
>> new: style-tile/index.html

Running "jshint:all" (jshint) task
Linting js/main.js...ERROR
[L1:C26] Expected ')' and instead saw 's'.
console.log('Sitename's Blah');
[L1:C27] Missing semicolon.
console.log('Sitename's Blah');
[L1:C31] Unclosed string.
console.log('Sitename's Blah');
>> Cannot read property 'id' of undefined

Warning: Task "jshint:all" failed. Used --force, continuing.
```

Deleted the one I set up and re-set it up without the apostrophe and it worked with no errors.

FYI
scott

**Comment by Snugug** [comment]
Thanks for the report. There are some big updates I want to make to SPs, unfortunately they require a bunchof other work first. This bug fix will be put in the queue

**Comment by Snugug** [comment]
This is no longer an issue in 2.0
