### ISSUE TITLE
Grunt / SASS Build Error

### ISSUE THREAD

**Issue by mkircher** [north/generator-style-prototype#51]
All, I installed a fresh copy as described and made sure the required SASS version (3.3.0.rc.6) was installed. While running the grunt server command, I got the following:

```
Running "server" task

Running "bundler" task

Running "exec:bundle:." (exec) task
Fetching gem metadata from https://rubygems.org/..............
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Using rake (10.1.1)
Using chunky_png (1.3.0)
Using multi_json (1.9.0)

Gem::Installer::ExtensionBuildError: ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby mkrf_conf.rb 
Ensuring you have the right version of listen installed.
Installing listen >= 1.1.0, < 3.0.0
Building native extensions.  This could take a while...
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/ext/builder.rb:60:in `run': ERROR: Failed to build gem native extension. (Gem::Installer::ExtensionBuildError)

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: invalid option -G  (-h will show valid options) (RuntimeError)


Gem files will remain installed in /Users/kirchr/Projects/Hrvst/Style Guide/.vendor/ruby/2.0.0/gems/nio4r-1.0.0 for inspection.
Results logged to /Users/kirchr/Projects/Hrvst/Style Guide/.vendor/ruby/2.0.0/gems/nio4r-1.0.0/ext/nio4r/gem_make.out
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/ext/ext_conf_builder.rb:37:in `block in build'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/tempfile.rb:324:in `open'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/ext/ext_conf_builder.rb:18:in `build'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/installer.rb:678:in `block (2 levels) in build_extensions'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/installer.rb:677:in `chdir'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/installer.rb:677:in `block in build_extensions'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/installer.rb:652:in `each'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/installer.rb:652:in `build_extensions'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/installer.rb:218:in `install'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency_installer.rb:372:in `block in install'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency_installer.rb:332:in `each'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency_installer.rb:332:in `each_with_index'
    from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency_installer.rb:332:in `install'
    from mkrf_conf.rb:18:in `<main>'


Gem files will remain installed in /Users/kirchr/Projects/Hrvst/Style Guide/.vendor/ruby/2.0.0/gems/sass-3.3.0.rc.6 for inspection.
Results logged to /Users/kirchr/Projects/Hrvst/Style Guide/.vendor/ruby/2.0.0/gems/sass-3.3.0.rc.6/ext/gem_make.out
An error occurred while installing sass (3.3.0.rc.6), and Bundler cannot
continue.
Make sure that `gem install sass -v '3.3.0.rc.6'` succeeds before bundling.
>> Exited with code: 5.

```

I'm not a gem or terminal expert, so any help would be great

**Comment by Snugug** [comment]
It appears as if the XCode Command Line Tools (freely available) are a requirement for installing Sass. Please install them and Sass should compile correctly.

**Comment by mkircher** [comment]
I've verified that everything is installed correctly including XCode CLT, registering as a Apple dev and downloading the tools...

```
Antilles:Style Guide kirchr$ xcode-select -p
/Applications/Xcode.app/Contents/Developer

Antilles:Style Guide kirchr$ gcc --version
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/c++/4.2.1
Apple LLVM version 5.0 (clang-500.2.79) (based on LLVM 3.3svn)
Target: x86_64-apple-darwin13.1.0
Thread model: posix
```

Unfortunately that didn't remedy the issue. Is there something else I am missing here?

**Comment by Snugug** [comment]
See if you can follow the new Installation Instructions to ensure that your Ruby version is up-to-date and ready to work with Style Prototypes. Then try running Bundle Install again.

2.0 of Style Prototypes changes how this loop works (it's no longer there, done once on install time and that's it)
