### ISSUE TITLE
Cannot find module './build/Release/shell'

### ISSUE THREAD

**Issue by matheusbaumgart** [north/generator-style-prototype#69]
Hi, After running the generator I'm getting the following error:

```
readline.js:924
            throw err;
            ^

Error: Cannot find module './build/Release/shell'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/generator-style-prototype/node_modules/execSync/index.js:30:11)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
```

Any idea? 
Thanks.

**Comment by ericmotil** [comment]
I'm getting the same error, have you found a fix for this?

**Comment by matheusbaumgart** [comment]
Anyone?
